plugin {
    touch_gestures {

        # Make small flicks trigger
        sensitivity = 14.0          # much higher
        workspace_swipe_fingers = 4
        workspace_swipe_edge = 0
        long_press_delay = 150
        edge_margin = 15
        emulate_touchpad_swipe = false

        # 4-finger → FAST Normal Workspace
        hyprgrass-bind = , swipe:4:l, exec, hyprctl dispatch workspace e-1
        hyprgrass-bind = , swipe:4:r, exec, hyprctl dispatch workspace e+1

        # 3-finger → Special (WASD)
        hyprgrass-bind = , swipe:3:u, exec, ~/.config/hypr/scripts/toggle-special-record.sh scratchfour
        hyprgrass-bind = , swipe:3:r, exec, ~/.config/hypr/scripts/toggle-special-record.sh scratchthree
        hyprgrass-bind = , swipe:3:d, exec, ~/.config/hypr/scripts/toggle-special-record.sh magic
        hyprgrass-bind = , swipe:3:l, exec, ~/.config/hypr/scripts/toggle-special-record.sh scratchone


        # Swipe up-left
        hyprgrass-bind = , swipe:3:lu, exec, ~/dotfiles/hypr-exp/.config/hypr/scripts/toggle-special.sh

        # Swipe up-right
        hyprgrass-bind = , swipe:3:ru, exec, ~/dotfiles/hypr-exp/.config/hypr/scripts/toggle-special.sh

    }
}

