
[opener]
nvim = [
  { run = "nvim \"$@\"", block = true }
]
zathura = [
  { run = "zathura \"$@\"", orphan = true }
]
# xournalpp = [
#   { run = "flatpak run com.github.xournalpp.xournalpp \"$@\"", orphan = true }
# ]

xournalpp = [
  { run = "fix-xopp \"$@\"; flatpak run com.github.xournalpp.xournalpp \"$@\"", orphan = true }
]


[open]
rules = [
# empty files
  { mime = "inode/x-empty", use = "nvim" },

  { mime = "application/pdf", use = "zathura" },
  { url = "*.pdf", use = "zathura" },

  { url = "*.xopp", use = "xournalpp" },

  { url = "*.fish", use = "nvim" },

  { mime = "text/*", use = "nvim" },
  { url = "*.md", use = "nvim" },

  { mime = "application/x-typst", use = "nvim" },
  { mime = "text/x-typst", use = "nvim" },
  { url = "*.typ", use = "nvim" },

  { url = "*.lua", use = "nvim" },
  { url = "*.cpp", use = "nvim" },
  { url = "*.h", use = "nvim" },
  { url = "*.py", use = "nvim" },
  { url = "*.rs", use = "nvim" },
  { url = "*.json", use = "nvim" },
  { url = "*.toml", use = "nvim" },

  # Final fallback
  { url = "*", use = "nvim" },
]

